// Uncle has decided to serve an omakase option, and output a menu based on customer's input.

// the input should either be "rice" or "noodle"

var omakaseGenerator = function (foodType) {
  // the generator will pick either 2 random rice or 2 random noodle dishes.

  // the generator can also switch one of the two dishes to roti prata.

  // create numbered variables to store the food names. e.g. chicken rice, nasi lemak etc.

  var choiceOne = "chicken rice";
  var choiceTwo = "nasi lemak";
  var choiceThree = "bak kut teh";
  var choiceFour = "roti prata";
  var choiceFive = "hokkien mee";
  var choiceSix = "laksa";
  var choiceSeven = "beef hor fun";

  // create a number generator function to decide which choice will be selected for rice + roti prata.

  var generateRiceNumber = function () {
    return Math.floor(Math.random() * 4) + 1;
  };

  var generateRiceNumberNoRoti = function () {
    return Math.floor(Math.random() * 3) + 1;
  };

  // create another number generate function for noodle + roti prata.

  var generateNoodleNumber = function () {
    return Math.floor(Math.random() * 4) + 4;
  };

  var generateNoodleNumberNoRoti = function () {
    return Math.floor(Math.random() * 3) + 5;
  };

  // link the number generator with the foodType using if else statements.

  if (foodType == "rice") {
    // create a variable for the first dish to store the number generated by the rice number generator.

    var firstRiceDish = generateRiceNumber();

    // link the first rice dish number with its respective dish variable.

    if (firstRiceDish == 1) {
      firstRiceDish = choiceOne;
    } else if (firstRiceDish == 2) {
      firstRiceDish = choiceTwo;
    } else if (firstRiceDish == 3) {
      firstRiceDish = choiceThree;
    } else if (firstRiceDish == 4) {
      firstRiceDish = choiceFour;
    }

    // If roti prata (4) was selected as the first dish, it must be removed from the equation.

    // create a second variable for the second dish to store the number generated by the rice number generator.

    if (firstRiceDish == choiceFour) {
      var secondRiceDish = generateRiceNumberNoRoti();
    } else {
      var secondRiceDish = generateRiceNumber();
    }

    // link the second rice dish number with its respective dish variable.

    if (secondRiceDish == 1) {
      secondRiceDish = choiceOne;
    } else if (secondRiceDish == 2) {
      secondRiceDish = choiceTwo;
    } else if (secondRiceDish == 3) {
      secondRiceDish = choiceThree;
    } else if (secondRiceDish == 4) {
      secondRiceDish = choiceFour;
    }

    var riceDishesChosen = `The chef has decided ${firstRiceDish} and ${secondRiceDish} as your omakase options! Please Enjoy!`;

    console.log(secondRiceDish);

    return riceDishesChosen;
  }

  // repeat same steps for noodles.
  else if (foodType == "noodle") {
    var firstNoodleDish = generateNoodleNumber();

    if (firstNoodleDish == 4) {
      firstNoodleDish = choiceFour;
    } else if (firstNoodleDish == 5) {
      firstNoodleDish = choiceFive;
    } else if (firstNoodleDish == 6) {
      firstNoodleDish = choiceSix;
    } else if (firstNoodleDish == 7) {
      firstNoodleDish = choiceSeven;
    }

    if (firstNoodleDish == choiceFour) {
      var secondNoodleDish = generateNoodleNumberNoRoti();
    } else {
      var secondNoodleDish = generateNoodleNumber();
    }

    if (secondNoodleDish == 4) {
      secondNoodleDish = choiceFour;
    } else if (secondNoodleDish == 5) {
      secondNoodleDish = choiceFive;
    } else if (secondNoodleDish == 6) {
      secondNoodleDish = choiceSix;
    } else if (secondNoodleDish == 7) {
      secondNoodleDish = choiceSeven;
    }

    var noodleDishesChosen = `The chef has decided ${firstNoodleDish} and ${secondNoodleDish} as your omakase options! Please Enjoy!`;

    return noodleDishesChosen;
  }
};
